### ISSUE TITLE
Error building documentation for AWS::Serverless::LayerVersion

### ISSUE THREAD

**Issue by vserecun** [horietakehiro/cfn-docgen#3]
Currently there is error to build documentation for resource type `AWS::Serverless::LayerVersion`

Example:
```yaml
Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLayer
      CompatibleArchitectures: ["arm64"]
      ContentUri: .
      CompatibleRuntimes:
        - "python3.13"
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: "python3.13"
```

I get the following output:

```
[WARNING] failed to build CfnTemplateResourceNode for resource [LambdaLayer]
[INFO] successfully generate document [./test.md] from template [./template.yaml]
```

Even though the sam build command works perfectly.
